# coding: utf-8

"""
    NBA v3 Odds

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import sportsdata_sdk_odds
from sportsdata_sdk_odds.model.team_game_trends import TeamGameTrends  # noqa: E501
from sportsdata_sdk_odds.rest import ApiException


class TestTeamGameTrends(unittest.TestCase):
    """TeamGameTrends unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTeamGameTrends(self):
        """Test TeamGameTrends"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sportsdata_sdk_odds.models.team_game_trends.TeamGameTrends()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
