# coding: utf-8

# flake8: noqa
"""
    NBA v3 Odds

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from sportsdata_sdk.model.betting_entity_metadata import BettingEntityMetadata
from sportsdata_sdk.model.betting_event import BettingEvent
from sportsdata_sdk.model.betting_market import BettingMarket
from sportsdata_sdk.model.betting_market_result import BettingMarketResult
from sportsdata_sdk.model.betting_market_split import BettingMarketSplit
from sportsdata_sdk.model.betting_outcome import BettingOutcome
from sportsdata_sdk.model.betting_outcome_result import BettingOutcomeResult
from sportsdata_sdk.model.betting_split import BettingSplit
from sportsdata_sdk.model.consensus_outcome import ConsensusOutcome
from sportsdata_sdk.model.game import Game
from sportsdata_sdk.model.game_betting_split import GameBettingSplit
from sportsdata_sdk.model.game_info import GameInfo
from sportsdata_sdk.model.game_odd import GameOdd
from sportsdata_sdk.model.matchup_trends import MatchupTrends
from sportsdata_sdk.model.player_prop import PlayerProp
from sportsdata_sdk.model.quarter import Quarter
from sportsdata_sdk.model.series import Series
from sportsdata_sdk.model.sportsbook import Sportsbook
from sportsdata_sdk.model.team_game_trends import TeamGameTrends
from sportsdata_sdk.model.team_trends import TeamTrends
from sportsdata_sdk.model.news import News
from sportsdata_sdk.model.opponent_season import OpponentSeason
from sportsdata_sdk.model.player import Player
from sportsdata_sdk.model.referee import Referee
from sportsdata_sdk.model.season import Season
from sportsdata_sdk.model.stadium import Stadium
from sportsdata_sdk.model.standing import Standing
from sportsdata_sdk.model.team import Team
from sportsdata_sdk.model.team_game import TeamGame
from sportsdata_sdk.model.team_season import TeamSeason